#pragma config(Sensor, S2,     ultrasonic,     sensorNone)
#pragma config(Sensor, S3,     light,          sensorEV3_Color)
#pragma config(Sensor, S4,     touch,          sensorEV3_Touch)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int lightVal;
int darkVal;
int sum;
int t;

void autoThreshold() {

	while (SensorValue(touch) != 1) {
		displayBigTextLine(5, "Read Light Value");
	}

	lightVal = SensorValue(light);
	eraseDisplay();

	while (SensorValue(touch) != 1) {
		displayBigTextLine(5, "Read Dark Value");
	}

	darkVal = SensorValue(light);
	eraseDisplay();

	sum = lightVal + darkVal;
	t = sum / 2;
}

task main() {

	autoThreshold();

	while (SensorValue(ultrasonic) > 10) {
		if (SensorValue(light) > t) {
			setMotorSpeed(right, 15);
		}
		else {
			setMotorSpeed(left, 15);
		}
	}

	setMotorSpeed(left, 0);
	setMotorSpeed(right, 0);
}
