#pragma config(Sensor, S2,     sonar,          sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     color,          sensorEV3_Color)
#pragma config(Sensor, S4,     touch,          sensorEV3_Touch)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float threshold;

void autoThreshold() {
	while (SensorValue(touch) != 1) {
		displayBigTextLine(5, "Read Light");
	}

	int light = SensorValue(color);
	eraseDisplay();
	sleep(1000);

	while (SensorValue(touch) != 1) {
		displayBigTextLine(5, "Read Dark");
	}

	int dark = SensorValue(color);
	sleep(1000);

	int sum = light + dark;
	threshold = sum / 2;
}

task main()
{
	autoThreshold();

	while (SensorValue(sonar) > 10) {
		if (SensorValue(color) > threshold) {
			setMotorSpeed(left, 0);
			setMotorSpeed(right, 15);
		}
		else {
			setMotorSpeed(right, 0);
			setMotorSpeed(left, 15);
		}
	}
}
