#pragma config(Sensor, S2,     sonar,          sensorNone)
#pragma config(Sensor, S3,     color,          sensorNone)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int threshold = 20;

void _stop() {
	setMotorSpeed(left, 0);
	setMotorSpeed(right, 0);
}

void lookForCheeseLeg1(int speed, int time) {


	setMotorSpeed(left, speed);
	setMotorSpeed(right, speed);

	sleep(time);

	if (SensorValue(color) < threshold) {
			_stop();
			displayBigTextLine(4, "Eat Some Cheese");
			sleep(10000000);
	}
}

void lookForCheeseLeg2() {

	setMotorSpeed(left, -60);
	setMotorSpeed(right, -60);
	sleep(1175);

	setMotorSpeed(right, 60);
	sleep(330);

	setMotorSpeed(left, 60);
	setMotorSpeed(right, 60);
	sleep(1200);

	setMotorSpeed(right, 60);
	sleep(330);

	setMotorSpeed(left, 60);
	setMotorSpeed(right, 60);
	sleep(700);

	if (SensorValue(color) < threshold) {
		_stop();
		displayBigTextLine(4, "Eat Some Cheese");
		sleep(1000000000);
	}
}

void lookForCheeseLeg3() {

}

task main()
{
	//Leg 1:
	lookForCheeseLeg1(60, 2400);

	//If leg 1 wasn't found, leg 2:
	lookForCheeseLeg2();

	//If leg 2 wasn't found, leg 3:
}
