#pragma config(Sensor, S2,     sonar,          sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     color,          sensorEV3_Color)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int threshold = 20;

void stopMotors() {
	setMotorSpeed(left, 0);
	setMotorSpeed(right, 0);
}

void checkCheese() {
	if (SensorValue(color) < threshold) {
			stopMotors();
			displayBigTextLine(4, "Eat Some Cheese");
			sleep(10000000);
	}
}

void lookForCheeseLeg1(int speed, int time) {


	setMotorSpeed(left, speed);
	setMotorSpeed(right, speed);

	sleep(time);

	if (SensorValue(color) < threshold) {
			stopMotors();
			displayBigTextLine(4, "Eat Some Cheese");
			sleep(10000000);
	}
}

void lookForCheeseLeg2() {
	setMotorSpeed(left, -60);
	setMotorSpeed(right, -60);
	sleep(1175);

	setMotorSpeed(left, 0);
	setMotorSpeed(right, 60);
	sleep(680);

	setMotorSpeed(left, 60);
	setMotorSpeed(right, 60);
	sleep(2000);

	setMotorSpeed(left, 0);
	setMotorSpeed(right, 60);
	sleep(620);

	setMotorSpeed(left, 60);
	setMotorSpeed(right, 60);
	sleep(1400);

	checkCheese();
}

void lookforCheeseLeg3() {
	setMotorSpeed(left, -60);
	setMotorSpeed(right, 60);
	sleep(1000);

	setMotorSpeed(left, 60);
	setMotorSpeed(right, 60);
	sleep(2000);

	setMotorSpeed(right, 0);
	setMotorSpeed(left, 60);
	sleep(640);

	setMotorSpeed(left, 60);
	setMotorSpeed(right, 60);
	sleep(600);

	checkCheese();
}

task main()
{
	//Leg 1:
	lookForCheeseLeg1(60, 2400);

	//If leg 1 wasn't found, leg 2:
	lookForCheeseLeg2();

	//if leg 2 wasn't found: leg 3:
	lookforCheeseLeg3();
}
