#pragma config(Sensor, S2,     sonar,          sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     light,          sensorEV3_Color)
#pragma config(Sensor, S4,     touch,          sensorEV3_Touch)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
	%d - integers
*/

int value1;
int value2;

void reverse() {

	setMotorSpeed(left, -50);
	setMotorSpeed(right, -50);
	sleep(5000);

	value2 = SensorValue(light);
	setMotorSpeed(left, 0);
	setMotorSpeed(right, 0);
	sleep(1000);
}

void sonar1() {
	while (SensorValue(sonar) > 10) {
		setMotorSpeed(left, 50);
		setMotorSpeed(right, 50);
	}

	value1 = SensorValue(light);

	reverse();
}

void idle() {

	while (SensorValue(touch) == 0) {

	}
}

task main() {

	idle();
	sonar1();
	eraseDisplay();

	displayBigTextLine(5, "%d", value2);
	displayBigTextLine(7, "%d", value1);
	sleep(1000000);
}
