#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          righMotor,     tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
	motorB: left motor
	motorC: right motor
*/

task main()
{
	//Forward
	motor[motorB] = 75;
	motor[motorC] = 75;
	wait1Msec(1550);

	//90 degree spin turn
	motor[motorC] = 50;
	motor[motorB] = -50;
	wait1Msec(460);

	//Forward
	motor[motorB] = 75;
	motor[motorC] = 75;
	wait1Msec(2200);

	//90 degree spin turn
	motor[motorC] = 50;
	motor[motorB] = -50;
	wait1Msec(450);

	//Forward
	motor[motorB] = 75;
	motor[motorC] = 75;
	wait1Msec(1650);

	//90 degree spin turn
	motor[motorC] = 50;
	motor[motorB] = -50;
	wait1Msec(485);

	//Forward
	motor[motorB] = 75;
	motor[motorC] = 75;
	wait1Msec(1200);

	//90 degree spin turn
	motor[motorC] = 50;
	motor[motorB] = -50;
	wait1Msec(450);

	//Forward
	motor[motorB] = 75;
	motor[motorC] = 75;
	wait1Msec(750);

	//Stop (uses setMotorSpeed and sleep commands)
	setMotorSpeed(motorC, 0);
	setMotorSpeed(motorB, 0);
	sleep(1000);

	//Backward
	motor[motorB] = -75;
	motor[motorC] = -75;
	wait1Msec(750);

	//90 degree spin turn
	motor[motorC] = 50;
	motor[motorB] = -50;
	wait1Msec(490);

	//Forward
	setMotorSpeed(motorC, 75);
	setMotorSpeed(motorB, 75);
	sleep(1200);

	//90 Degree Turn Left
	setMotorSpeed(motorC, -50);
	setMotorSpeed(motorB, 50);
	sleep(490);

	//Forward
	setMotorSpeed(motorC, 75);
	setMotorSpeed(motorB, 75);
	sleep(2600);

	//90 Degree Turn Left
	setMotorSpeed(motorC, -50);
	setMotorSpeed(motorB, 50);
	sleep(500);

	//Forward
	setMotorSpeed(motorC, 75);
	setMotorSpeed(motorB, 75);
	sleep(1400);

	//Dance
	setMotorSpeed(motorC, 100);
	setMotorSpeed(motorB, -100);
	sleep(3000);
}
