#pragma config(Sensor, S1,     color,          sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S2,     touch,          sensorEV3_Touch)
#pragma config(Sensor, S3,     sonar,          sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void wallTouch() {
	while (SensorValue(touch) != 1) {
		setMotorSpeed(left, 50);
		setMotorSpeed(right, 50);
	}

	setMotorSpeed(left, 0);
	setMotorSpeed(right, 0);
	sleep(500);

	setMotorSpeed(left, -50);
	setMotorSpeed(right, -50);
	sleep(1500);
}

void leftTurn() {
	setMotorSpeed(left, 0);
	setMotorSpeed(right, 50);
	sleep(720);
}

void rightTurn() {
	setMotorSpeed(right, 0);
	setMotorSpeed(left, 50);
	sleep(850);
}

void moveForward(int ms) {
	setMotorSpeed(left, 50);
	setMotorSpeed(right, 50);
	sleep(ms);
}

void lineTrack() {
	while (SensorValue(color) != 5) {
		if (SensorValue(color) == 1) {
			setMotorSpeed(left, 0);
			setMotorSpeed(right, 20);
		}
		else {
			setMotorSpeed(right, 0);
			setMotorSpeed(left, 20);
		}
	}
}

void ultrasonic(int cm) {
	while (SensorValue(sonar) > cm) {
		setMotorSpeed(left, 50);
		setMotorSpeed(right, 50);
	}

	setMotorSpeed(left, 0);
	setMotorSpeed(right, 0);
	sleep(2000);
}

task main()
{
	wallTouch();
	leftTurn();
	moveForward(750);
	lineTrack();
	rightTurn();
	ultrasonic(15);
	rightTurn();
	ultrasonic(15);

	setMotorSpeed(left, 50);
	setMotorSpeed(right, 0);
	sleep(800);

	ultrasonic(10);
	leftTurn();

	setMotorSpeed(left, 50);
	setMotorSpeed(right, 50);
	sleep(200);
}
