#pragma config(Sensor, S1,     touch,          sensorEV3_Touch)
#pragma config(Sensor, S2,     sonar,          sensorEV3_Ultrasonic)
#pragma config(Sensor, S3,     ,               sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     ,               sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Goes forward until the ultrasonic sensor detects that it is close to the wall:
void goForwardUltrasonic()
{
	while (SensorValue(sonar) > 19)
	{
		setMotorSpeed(left, 50);
		setMotorSpeed(right, 50);
  }
}

//Goes forward until the touch sensor detects that it has touched the wall:
void goForwardTouch() {
	while (SensorValue(touch) == 0) {
		setMotorSpeed(left, 50);
		setMotorSpeed(right, 50);
	}
}

//Constant distance back:
void goBack() {
	setMotorSpeed(left, -50);
	setMotorSpeed(right, -50);
	sleep(400);
}

//Constant 90 degree turn left:
void rightAngleTurnLeft() {
	setMotorSpeed(left, 0);
	setMotorSpeed(right, 50);
	sleep(685);
}

task main()
{
	//Ultrasonic Lap:
	goForwardUltrasonic();
	rightAngleTurnLeft();
	goForwardUltrasonic();
	rightAngleTurnLeft();
	goForwardUltrasonic();
	rightAngleTurnLeft();
	goForwardUltrasonic();
	rightAngleTurnLeft();

	//Touch Lap:
	goForwardTouch();
	goBack();
	rightAngleTurnLeft();
	goForwardTouch();
	goBack();
	rightAngleTurnLeft();
	goForwardTouch();
	goBack();
	rightAngleTurnLeft();
	goForwardTouch();
	goBack();
	rightAngleTurnLeft();
}
