#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void reset() {
	resetMotorEncoder(left);
	resetMotorEncoder(right);
}

void _forward(int degrees) {
	setMotorTarget(left, degrees, 50);
	setMotorTarget(right, degrees, 50);
	waitUntilMotorStop(left);
	waitUntilMotorStop(right);
	reset();
}

void _right(int degrees) {
	setMotorTarget(left, degrees, 50);
	waitUntilMotorStop(left);
	reset();
}

void _left(int degrees) {
	setMotorTarget(right, degrees, 50);
	waitUntilMotorStop(right);
	reset();
}

task main()
{
	reset();
	_forward(1000);
	_left(390);
	_forward(1300);
	_right(390);
	_forward(1000);
	_right(410);
	_forward(1300);
	_left(390);
	_forward(500);
	_left(400);
	_forward(1300);
	_right(390);
	_forward(1200);
}
