#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//setMotorSync(master, slave, turn ratio, power);
task main()
{
	//Goes straight
	setMotorSync(left, right, 0, 75);
	sleep(1300);

	//Swing turn left
	setMotorSync(left, right, -25, 75);
	sleep(800);

	//Go straight
	setMotorSync(left, right, 0, 75);
	sleep(1350);

	//Swing turn right
	setMotorSync(left, right, 25, 75);
	sleep(1600);

	//Go straight
	setMotorSync(left, right, 0, 75);
	sleep(1300);

	//Swing turn left
	setMotorSync(left, right, -25, 75);
	sleep(1700);

	//Go straight
	setMotorSync(left, right, 0, 75);
	sleep(1400);

	//Swing turn right
	setMotorSync(left, right, 25, 75);
	sleep(900);

	//Go straight
	setMotorSync(left, right, 0, 75);
	sleep(900);
}
