#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
	motorC: right motor
	motorB: left motor
*/

task main()
{
	//Pushes both motors forward at 50 perent speed:
	motor[motorC] = 50;
	motor[motorB] = 50;
	wait1Msec(2050);

	//Spin turn:
	motor[motorC] = 50;
	motor[motorB] = -50;
	wait1Msec(490);

	//Pushes both motors forward at 50 perent speed:
	motor[motorC] = 50;
	motor[motorB] = 50;
	wait1Msec(1800);

	//Spin turn:
	motor[motorC] = 50;
	motor[motorB] = -50;
	wait1Msec(640);

	//Pushes both motors forward at 50 perent speed:
	motor[motorC] = 50;
	motor[motorB] = 50;
	wait1Msec(3000);
}
