#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void goForwardUntilTouch() {
	//Moves forward until the wall is touched:
	while (SensorValue(touchSensor) != 1) {
		setMotorSpeed(left, 50);
		setMotorSpeed(right, 50);
	}
}

void goBackward(int x) {
	//Moves backward:
	setMotorSpeed(left, -50);
	setMotorSpeed(right, -50);
	sleep(x);
}

void turn(bool isRight) {
	if (isRight == true) {
		//Pin turn right:
		setMotorSpeed(left, 50);
		sleep(380);
		return;
	}
	//Pin turn left:
	setMotorSpeed(right, 50);
	sleep(380);
}

//Goes forward at a specific power level and duration:
void goForwardCustom(int powerLevel, float ms) {
	setMotorSpeed(left, powerLevel);
	setMotorSpeed(right, powerLevel);
	sleep(ms);
}

task main()
{
	goForwardUntilTouch();
	goBackward(1600);
	turn(false);
	goForwardUntilTouch();
	goBackward(300);
	turn(true);
	goForwardUntilTouch();
	goBackward(300);
	turn(true);
	goForwardCustom(50, 1500);
}
