#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//Moves forward until the wall is touched:
	while (SensorValue(touchSensor) != 1) {
		setMotorSpeed(left, 50);
		setMotorSpeed(right, 50);
	}

	//Moves backward:
	setMotorSpeed(left, -50);
	setMotorSpeed(right, -50);
	sleep(1600);

	//Pin turn left:
	setMotorSpeed(right, 50);
	sleep(370);

	//Moves forward until the wall is touched:
	while (SensorValue(touchSensor) != 1) {
		setMotorSpeed(left, 50);
		setMotorSpeed(right, 50);
	}

	//Moves backward:
	setMotorSpeed(left, -50);
	setMotorSpeed(right, -50);
	sleep(450);

	//Pin turn right:
	setMotorSpeed(left, 50);
	sleep(370);

	//Moves forward until the wall is touched:
	while (SensorValue(touchSensor) != 1) {
		setMotorSpeed(left, 50);
		setMotorSpeed(right, 50);
	}

	//Moves backward:
	setMotorSpeed(left, -50);
	setMotorSpeed(right, -50);
	sleep(300);

	//Pin turn right:
	setMotorSpeed(left, 50);
	sleep(370);

	//Moves forward:
	setMotorSpeed(left, 50);
	setMotorSpeed(right, 50);
	sleep(1300);
}
