#pragma config(Sensor, S2,     touch,          sensorEV3_Touch)
#pragma config(Sensor, S1,     light,          sensorEV3_Color)
#pragma config(Sensor, S3,     sonar,          sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int lightVal;
int darkVal;
int sum;
int t;

void autoThreshold() {

	while (SensorValue(touch) != 1) {
		displayBigTextLine(5, "Read Light Value");
	}

	lightVal = SensorValue(light);
	eraseDisplay();

	sleep(1000);

	while (SensorValue(touch) != 1) {
		displayBigTextLine(5, "Read Dark Value");
	}

	darkVal = SensorValue(light);
	eraseDisplay();

	sum = lightVal + darkVal;
	t = sum / 2;
}

void lineCounter(int lines) {
	int countedLines = 0;
	int seenLight = 1;

	while (countedLines < lines) {
		setMotorSpeed(left, 40);
		setMotorSpeed(right, 40);

		if (SensorValue(light) <= t) {
			if (seenLight == 1) {
				countedLines = countedLines + 1;
				seenLight = 0;
			}
		}
		else {
			seenLight = 1;
		}
	}

	countedLines = 0;
	sleep(500);
}

void leftTurn() {
	setMotorSpeed(left, 50);
	setMotorSpeed(right, 50);
	sleep(200);

	setMotorSpeed(left, 0);
	setMotorSpeed(right, 50);
	sleep(720);
}

void rightTurn() {
	setMotorSpeed(left, 50);
	setMotorSpeed(right, 50);
	sleep(200);

	setMotorSpeed(right, 0);
	setMotorSpeed(left, 50);
	sleep(720);
}

void wallTouch() {
	while (SensorValue(touch) != 1) {
		setMotorSpeed(left, 50);
		setMotorSpeed(right, 50);
	}

	setMotorSpeed(left, -50);
	setMotorSpeed(right, -50);
	sleep(600);
}

void ultrasonic(int cm) {
	while (SensorValue(sonar) > cm) {
		setMotorSpeed(left, 50);
		setMotorSpeed(right, 50);
	}

	setMotorSpeed(left, 0);
	setMotorSpeed(right, 0);
}

void display() {
	setMotorSpeed(left, 0);
	setMotorSpeed(right, 0);
	displayBigTextLine(3, "Warehouse");
	displayBigTextLine(5, "Challenge Complete");
	sleep(1000000);
}

task main()
{
	autoThreshold();
	lineCounter(5);
	leftTurn();
	wallTouch();
	leftTurn();
	lineCounter(3);
	leftTurn();
	ultrasonic(15);
	leftTurn();
	wallTouch();
	display();
}
